ALTER TABLE tblcurrencies
    ADD rate decimal(8, 2) NULL;
ALTER TABLE tblcurrencies
    MODIFY COLUMN isdefault tinyint(1) NOT NULL DEFAULT '0' AFTER rate;

CREATE TABLE tblpositions
(
    id   int auto_increment primary key,
    name varchar(100) not null
) engine = MyISAM;

CREATE TABLE tbllevels
(
    id           int auto_increment primary key,
    level        int            not null,
    departmentid int            not null,
    positionid   int            not null,
    fromamount   decimal(20, 2) not null,
    toamount     decimal(20, 2) not null,
    gp           decimal(8, 2)  not null
) engine = MyISAM;

CREATE TABLE tblstafflevels
(
    stafflevelid int auto_increment primary key,
    staffid      int not null,
    levelid      int not null
) engine = MyISAM;

ALTER TABLE tblestimates
    ADD lcycost decimal(20, 2) NULL;

ALTER TABLE tblestimates
    ADD lcyprofit decimal(8, 2) NULL;

ALTER TABLE tblestimates
    ADD departmentid INT NOT NULL;

ALTER TABLE tblestimates
    ADD approvedlevel INT NOT NULL;

ALTER TABLE tblestimates
    ADD currentlevel INT NOT NULL;

INSERT INTO tblemailtemplates (type, slug, language, name, subject, message, fromname, fromemail, plaintext, active,
                               `order`)
VALUES ('estimate', 'estimate-approve-request', 'english', 'Approval notification for Quotation',
        'Approval notification for Quotation', '<p class="p1">Dear Stephen Lee(full name),</p>
<p class="p2"></p>
<p class="p1">Below documents are waiting for approval:</p>
<p class="p2"></p>
<p class="p1"><a href="{estimate_link}">{estimate_number}</a>,</p>
<p class="p1">{client_company}，</p>
<p class="p1">{estimate_gp},&nbsp;</p>
<p class="p1">{estimate_total},</p>
<p class="p1">Available approver: Stephen Lee, Ada Wong.</p>
<p class="p2"></p>
<p class="p1">This email is generated by System. Don''t reply this email.</p>', '{companyname} | CRM', '', 0, 1, 0);

CREATE TABLE tblapprovedlogs
(
    id          int auto_increment primary key,
    estimateid  int not null,
    staffid     int not null,
    level       int not null,
    approvedate datetime,
    status      int not null
) engine = MyISAM;

create table tblopportunities
(
    id                        int auto_increment primary key,
    name                      varchar(600)   not null,
    description               text           null,
    status                    int default 0  not null,
    clientid                  int            not null,
    billing_type              int            not null,
    start_date                date           not null,
    deadline                  date           null,
    opportunity_created       date           not null,
    date_finished             datetime       null,
    progress                  int default 0  null,
    progress_from_tasks       int default 1  not null,
    opportunity_cost          decimal(15, 2) null,
    opportunity_rate_per_hour decimal(15, 2) null,
    estimated_hours           decimal(15, 2) null,
    addedfrom                 int            not null
) engine = MyISAM;

create table tblopportunitysettings
(
    id             int auto_increment primary key,
    opportunity_id int          not null,
    name           varchar(100) not null,
    value          text         null
) engine = MyISAM;

create table tblopportunitymembers
(
    id             int auto_increment primary key,
    opportunity_id int not null,
    staff_id       int not null
) engine = MyISAM;

create table tblpinnedopportunities
(
    id             int auto_increment primary key,
    opportunity_id int not null,
    staff_id       int not null
) engine = MyISAM;

create table tblopportunityactivity
(
    id                  int auto_increment primary key,
    opportunity_id      int           not null,
    staff_id            int default 0 not null,
    contact_id          int default 0 not null,
    fullname            varchar(100)  null,
    visible_to_customer int default 0 not null,
    description_key     varchar(500)  not null comment 'Language file key',
    additional_data     text          null,
    dateadded           datetime      not null
) engine = MyISAM;

ALTER TABLE tblvault
    ADD share_in_opportunities tinyint(1) default 0 not null;

create table tblopportunitynotes
(
    id             int auto_increment primary key,
    opportunity_id int  not null,
    content        text not null,
    staff_id       int  not null
) engine = MyISAM;

ALTER table tblmilestones
    ADD opportunity_id int null;

alter table tblmilestones
    modify project_id int null;

ALTER table tblexpenses
    ADD opportunity_id int null;

alter table tblexpenses
    modify project_id int null;

ALTER table tblinvoices
    ADD opportunity_id int null;

alter table tblinvoices
    modify project_id int null;

ALTER table tblcreditnotes
    ADD opportunity_id int null;

alter table tblcreditnotes
    modify project_id int null;

ALTER table tblestimates
    ADD opportunity_id int null;

alter table tblestimates
    modify project_id int null;

ALTER table tbltickets
    ADD opportunity_id int null;

alter table tbltickets
    modify project_id int null;

ALTER table tblsubscriptions
    ADD opportunity_id int null;

alter table tblsubscriptions
    modify project_id int null;

create table tblopportunitydiscussions
(
    id               int auto_increment primary key,
    opportunity_id   int                  not null,
    subject          varchar(500)         not null,
    description      text                 not null,
    show_to_customer tinyint(1) default 0 not null,
    datecreated      datetime             not null,
    last_activity    datetime             null,
    staff_id         int        default 0 not null,
    contact_id       int        default 0 not null
) engine = MyISAM;

create table tblopportunitydiscussioncomments
(
    id              int auto_increment primary key,
    discussion_id   int           not null,
    discussion_type varchar(10)   not null,
    parent          int           null,
    created         datetime      not null,
    modified        datetime      null,
    content         text          not null,
    staff_id        int           not null,
    contact_id      int default 0 null,
    fullname        varchar(300)  null,
    file_name       varchar(300)  null,
    file_mime_type  varchar(70)   null
) engine = MyISAM;

create table tblopportunityfiles
(
    id                  int auto_increment primary key,
    file_name           mediumtext           not null,
    subject             varchar(500)         null,
    description         text                 null,
    filetype            varchar(50)          null,
    dateadded           datetime             not null,
    last_activity       datetime             null,
    opportunity_id      int                  not null,
    visible_to_customer tinyint(1) default 0 null,
    staffid             int                  not null,
    contact_id          int        default 0 not null,
    external            varchar(40)          null,
    external_link       text                 null,
    thumbnail_link      text                 null
) engine = MyISAM;

INSERT INTO `tblpermissions` (`name`, `shortname`)
VALUES ('Opportunities', 'opportunities');

ALTER TABLE tblcontacts
    ADD opportunity_emails tinyint(1) default 1 not null;

create table tblcampaigntypes
(
    id   int auto_increment primary key,
    name varchar(150) not null
) engine = MyISAM;

create table tblcampaigns
(
    id            int auto_increment primary key,
    name          varchar(300)   not null,
    description   text           null,
    date_from     datetime       not null,
    date_to       datetime,
    budget_cost   decimal(11, 2) null,
    expected_sale decimal(11, 2) null
) engine = MyISAM;

alter table tblcampaigns
    add type_id int not null;

create table tblsalesstages
(
    id    int auto_increment primary key,
    name  varchar(300) not null,
    color varchar(100) not null default '#000000'
) engine = MyISAM;

alter table tblopportunities
    change clientid rel_id int not null;

alter table tblopportunities
    add rel_type varchar(40) not null default 'lead';

alter table tblopportunities
    add rel_to varchar(600);

alter table tblopportunities
    add amount decimal(11, 2) null;

alter table tblopportunities
    add sales_stage_id int not null;

alter table tblopportunities
    add probability decimal(11, 2) null;

alter table tblopportunities
    add nextstep varchar(500) null;

alter table tblopportunities
    add type varchar(200) not null;

alter table tblopportunities
    add source int not null;

alter table tblopportunities
    add campaign_id int not null;

alter table tblproposals
    add opportunity_id int null;

alter table tblprojects
    add opportunity_id int null;

create table tblopportunitycontacts
(
    id             int auto_increment primary key,
    opportunity_id int          not null,
    contact_id     int          not null,
    note           varchar(500) null
) engine = MyISAM;

create table tblsuppliersgroups
(
    id   int auto_increment primary key,
    name varchar(600) not null
) engine = MyISAM;

create table tblsuppliers
(
    id                     int auto_increment primary key,
    company                varchar(100)  null,
    vat                    varchar(50)   null,
    phonenumber            varchar(30)   null,
    country                int default 0 not null,
    city                   varchar(100)  null,
    zip                    varchar(15)   null,
    state                  varchar(50)   null,
    address                varchar(100)  null,
    website                varchar(150)  null,
    datecreated            datetime      not null,
    active                 int default 1 not null,
    billing_street         varchar(200)  null,
    billing_city           varchar(100)  null,
    billing_state          varchar(100)  null,
    billing_zip            varchar(100)  null,
    billing_country        int default 0 null,
    shipping_street        varchar(200)  null,
    shipping_city          varchar(100)  null,
    shipping_state         varchar(100)  null,
    shipping_zip           varchar(100)  null,
    shipping_country       int default 0 null,
    longitude              varchar(300)  null,
    latitude               varchar(300)  null,
    default_language       varchar(40)   null,
    default_currency       int default 0 not null,
    show_primary_contact   int default 0 not null,
    stripe_id              varchar(40)   null,
    registration_confirmed int default 1 not null,
    addedfrom              int default 0 not null
) engine = MyISAM;

create table tblsuppliergroups_in
(
    id          int auto_increment primary key,
    groupid     int not null,
    supplier_id int not null
) engine = MyISAM;

create table tblsuppliercontacts
(
    id                     int auto_increment primary key,
    supplier_id            int                  not null,
    is_primary             int        default 1 not null,
    firstname              varchar(300)         not null,
    lastname               varchar(300)         not null,
    email                  varchar(100)         not null,
    phonenumber            varchar(100)         not null,
    title                  varchar(200)         not null,
    datecreated            datetime             not null,
    password               varchar(255)         null,
    new_pass_key           varchar(32)          null,
    new_pass_key_requested datetime             null,
    last_ip                varchar(40)          null,
    last_login             datetime             null,
    last_password_change   datetime             null,
    active                 tinyint(1) default 1 not null,
    profile_image          varchar(300)         null,
    direction              varchar(3)           null
) engine = MyISAM;

create table tblsupplieradmins
(
    staff_id      int  not null,
    supplier_id   int  not null,
    date_assigned text not null
) engine = MyISAM;

create table tblcustomerwarehouses
(
    id        int auto_increment primary key,
    name      varchar(300) not null,
    address   varchar(500) null,
    contact   varchar(50)  null,
    telephone varchar(20)  null
) engine = MyISAM;

create table tblshipmentterms
(
    id   int auto_increment primary key,
    name varchar(300) not null
) engine = MyISAM;

create table tblpaymentterms
(
    id      int auto_increment primary key,
    name    varchar(300)            not null,
    deposit decimal(8, 2) default 0 null,
    days    int           default 0 null
) engine = MyISAM;

alter table tblcustomerwarehouses
    add clientid int not null;

create table tblpurchaseorders
(
    id                int auto_increment primary key,
    order_number      varchar(60)   not null,
    supplier          int           not null,
    clientid          int           not null,
    warehouse         int           not null,
    pe_number         varchar(50),
    po_date           datetime      not null,
    currency          int           not null,
    currency_rate     decimal(8, 2) not null,
    status            int           not null,
    payment_term      int           not null,
    shipment_term     int           not null,
    discount          decimal(8, 2) not null default 0,
    additional_charge decimal(8, 2) not null default 0,
    material          int,
    confirmed_at      datetime,
    production_at     datetime,
    departure_at      datetime,
    finished_at       datetime,
    created_at        datetime      not null,
    updated_at        datetime
) engine = MyISAM;

alter table tblpurchaseorders
    add addedfrom int not null;


alter table tblpurchaseorders
    add subtotal decimal(15, 2);

alter table tblpurchaseorders
    add discount_percent decimal(15, 2);

alter table tblpurchaseorders
    add discount_total decimal(15, 2);

alter table tblpurchaseorders
    add discount_type varchar(30);


alter table tblpurchaseorders
    add adjustment decimal(15, 2);

alter table tblpurchaseorders
    add total decimal(15, 2);

alter table tblpurchaseorders
    add show_quantity_as int;

alter table tblpurchaseorders
    add total_tax decimal(15, 2);

create table tblsupplierautologin
(
    key_id     char(32)                            not null,
    user_id    int                                 not null,
    user_agent varchar(150)                        not null,
    last_ip    varchar(40)                         not null,
    last_login timestamp default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP
) engine = MyISAM;

create table tblproductionlogs
(
    id       int auto_increment primary key,
    finished int default 0,
    shipped  int default 0,
    p_date   datetime
) engine = MyISAM;

alter table tblproductionlogs
    add item_id int;
